#!/usr/bin/env python3
"""Fetch full daily snow-water-equivalent history for the mapped SNOTEL
stations and write snotel-history.json, the committed data behind the
water-year overlay chart on snow stations.

    python3 fetch_snotel_history.py

Network: NRCS AWDB REST API (the same source the page queries live for the
current water year). Station list comes from system.json, so run
build_system.py first if stations changed.

Output shape, per station triplet:
  years:  {water_year: [366 floats or nulls]}  SWE inches by day of water year
  median: [366 floats or nulls]  per-day median across complete water years
  worst:  {"wy", "peak_in", "label_date", "label_i"}  the completed water year
          with the LOWEST PEAK snowpack; label_i is its peak's day index
"""

import json
import os
import statistics
import urllib.parse
import urllib.request
from datetime import date, datetime

HERE = os.path.dirname(os.path.abspath(__file__))
API = "https://wcc.sc.egov.usda.gov/awdbRestApi/services/v1/data"
DAYS_IN_WATER_YEAR = 366
SPIKE_THRESHOLD_IN = 2.0
MIN_DAYS_FOR_COMPLETE = 300
MIN_YEARS_FOR_MEDIAN = 5


def snotel_triplets():
    with open(os.path.join(HERE, "system.json")) as f:
        system = json.load(f)
    return [p["chart"]["triplet"] for p in system["points"] if p["kind"] == "snotel"]


def fetch_station_values(triplets):
    query = urllib.parse.urlencode({
        "stationTriplets": ",".join(triplets), "elements": "WTEQ",
        "duration": "DAILY", "beginDate": "1980-01-01",
        "endDate": date.today().isoformat(),
    })
    with urllib.request.urlopen(f"{API}?{query}") as response:
        payload = json.load(response)
    return {entry["stationTriplet"]: entry["data"][0]["values"]
            for entry in payload if entry.get("data")}


def water_year(day):
    return day.year + 1 if day.month >= 10 else day.year


def day_of_water_year(day):
    start = date(day.year if day.month >= 10 else day.year - 1, 10, 1)
    return (day - start).days


def traces_by_water_year(values):
    years = {}
    for row in values:
        value = row.get("value")
        if value is None or value < 0:
            continue
        day = datetime.fromisoformat(row["date"]).date()
        trace = years.setdefault(water_year(day), [None] * DAYS_IN_WATER_YEAR)
        index = day_of_water_year(day)
        if 0 <= index < DAYS_IN_WATER_YEAR:
            trace[index] = round(value, 1)
    return years


def despike(trace):
    cleaned = list(trace)
    for i in range(1, len(trace) - 1):
        prev, here, after = trace[i - 1], trace[i], trace[i + 1]
        if None in (prev, here, after):
            continue
        local = sorted((prev, here, after))[1]
        if abs(here - local) > SPIKE_THRESHOLD_IN:
            cleaned[i] = local
    return cleaned


def is_complete(trace):
    return sum(value is not None for value in trace) >= MIN_DAYS_FOR_COMPLETE


def median_trace(years):
    complete = [trace for trace in years.values() if is_complete(trace)]
    result = []
    for index in range(DAYS_IN_WATER_YEAR):
        values = [trace[index] for trace in complete if trace[index] is not None]
        result.append(round(statistics.median(values), 1)
                      if len(values) >= MIN_YEARS_FOR_MEDIAN else None)
    return result


def lowest_peak_year(years):
    current = water_year(date.today())
    complete = {wy: trace for wy, trace in years.items()
                if wy != current and is_complete(trace)}
    if not complete:
        return None
    def peak(trace):
        return max(v for v in trace if v is not None)
    wy = min(complete, key=lambda wy: peak(complete[wy]))
    trace = complete[wy]
    peak_index = max((i for i, v in enumerate(trace) if v is not None),
                     key=lambda i: trace[i])
    peak_day = date(wy - 1, 10, 1).toordinal() + peak_index
    return {"wy": wy, "peak_in": trace[peak_index], "label_i": peak_index,
            "label_date": date.fromordinal(peak_day).isoformat()}


def build():
    triplets = snotel_triplets()
    stations_values = fetch_station_values(triplets)
    output = {"_comment": "Generated by fetch_snotel_history.py. Do not edit.",
              "fetched": date.today().isoformat(), "stations": {}}
    for triplet in triplets:
        years = traces_by_water_year(stations_values.get(triplet, []))
        years = {wy: despike(trace) for wy, trace in years.items()}
        output["stations"][triplet] = {
            "years": {str(wy): trace for wy, trace in sorted(years.items())},
            "median": median_trace(years),
            "worst": lowest_peak_year(years),
        }
        print(triplet, len(years), "water years, lowest peak:",
              output["stations"][triplet]["worst"])
    path = os.path.join(HERE, "snotel-history.json")
    with open(path, "w") as f:
        json.dump(output, f, separators=(",", ":"))
    print("wrote", path, os.path.getsize(path) // 1024, "KB")


if __name__ == "__main__":
    build()
