#!/usr/bin/env python3
"""Fetch full daily storage history for the mapped reservoirs and write
storage-history.json, the committed data behind the water-year overlay chart.

    python3 fetch_storage_history.py

Network: Colorado DWR CDSS REST API (the same source the page queries live for
the last-12-months chart). Rerun rarely; history only grows by one day a day.

Output shape, per reservoir abbrev:
  years:  {water_year: [366 ints or nulls]}  storage in AF by day of water year
          (index 0 = Oct 1; Feb 29 folds into index for that date; missing
          days are null)
  median: [366 ints or nulls]  per-day median across all complete water years
  worst:  {"wy", "min_af", "min_date"}  the water year with the lowest minimum
"""

import json
import os
import statistics
import urllib.parse
import urllib.request
from datetime import date, datetime

HERE = os.path.dirname(os.path.abspath(__file__))
API = "https://dwr.state.co.us/Rest/GET/api/v2/telemetrystations/telemetrytimeseriesday/"
# Telemetry contains occasional garbage rows (values in the millions of AF).
# Anything above these bounds (comfortably above published capacity plus flood
# surcharge) is discarded as a sensor/transcription artifact.
SANITY_MAX_AF = {"DILRESCO": 300000, "CHERESCO": 100000,
                 "CHARESCO": 100000, "STRRESCO": 12000}
RESERVOIRS = list(SANITY_MAX_AF)
DAYS_IN_WATER_YEAR = 366
PAGE_SIZE = 50000


def fetch_all_days(abbrev):
    rows, page = [], 1
    while True:
        query = urllib.parse.urlencode({
            "format": "json", "abbrev": abbrev, "parameter": "STORAGE",
            "startDate": "1980-01-01", "endDate": date.today().isoformat(),
            "pageSize": PAGE_SIZE, "pageIndex": page,
        })
        with urllib.request.urlopen(f"{API}?{query}") as response:
            payload = json.load(response)
        rows.extend(payload.get("ResultList", []))
        if page >= payload.get("PageCount", 1):
            return rows
        page += 1


def water_year(day):
    return day.year + 1 if day.month >= 10 else day.year


def day_of_water_year(day):
    start = date(day.year if day.month >= 10 else day.year - 1, 10, 1)
    return (day - start).days


def traces_by_water_year(rows, max_af):
    years = {}
    for row in rows:
        value = row.get("measValue")
        if value is None or value <= 0 or value > max_af:
            continue
        day = datetime.fromisoformat(row["measDate"]).date()
        trace = years.setdefault(water_year(day), [None] * DAYS_IN_WATER_YEAR)
        index = day_of_water_year(day)
        if 0 <= index < DAYS_IN_WATER_YEAR:
            trace[index] = round(value)
    return years


def despike(trace, max_af):
    """Replace single-day excursions (sensor glitches) with the local median."""
    threshold = max_af * 0.08
    cleaned = list(trace)
    for i in range(1, len(trace) - 1):
        prev, here, after = trace[i - 1], trace[i], trace[i + 1]
        if None in (prev, here, after):
            continue
        local = sorted((prev, here, after))[1]
        if abs(here - local) > threshold:
            cleaned[i] = local
    return cleaned


def is_complete(trace):
    return sum(value is not None for value in trace) >= 300


def median_trace(years):
    complete = [trace for trace in years.values() if is_complete(trace)]
    result = []
    for index in range(DAYS_IN_WATER_YEAR):
        values = [trace[index] for trace in complete if trace[index] is not None]
        result.append(round(statistics.median(values)) if len(values) >= 5 else None)
    return result


def worst_year(years):
    current = water_year(date.today())
    complete = {wy: trace for wy, trace in years.items()
                if wy != current and is_complete(trace)}
    if not complete:
        return None
    def mean(trace):
        values = [v for v in trace if v is not None]
        return sum(values) / len(values)
    wy = min(complete, key=lambda wy: mean(complete[wy]))
    trace = complete[wy]
    low_index = min((i for i, v in enumerate(trace) if v is not None),
                    key=lambda i: trace[i])
    low_date = date(wy - 1, 10, 1).toordinal() + low_index
    return {"wy": wy, "min_af": trace[low_index],
            "min_date": date.fromordinal(low_date).isoformat()}


def build():
    output = {"_comment": "Generated by fetch_storage_history.py. Do not edit.",
              "fetched": date.today().isoformat(), "reservoirs": {}}
    for abbrev in RESERVOIRS:
        rows = fetch_all_days(abbrev)
        years = traces_by_water_year(rows, SANITY_MAX_AF[abbrev])
        years = {wy: despike(trace, SANITY_MAX_AF[abbrev])
                 for wy, trace in years.items()}
        output["reservoirs"][abbrev] = {
            "years": {str(wy): trace for wy, trace in sorted(years.items())},
            "median": median_trace(years),
            "worst": worst_year(years),
        }
        print(abbrev, len(rows), "days,", len(years), "water years,",
              "worst:", output["reservoirs"][abbrev]["worst"])
    path = os.path.join(HERE, "storage-history.json")
    with open(path, "w") as f:
        json.dump(output, f, separators=(",", ":"))
    print("wrote", path, os.path.getsize(path) // 1024, "KB")


if __name__ == "__main__":
    build()
